import Head from "next/head";
import { Inter } from "next/font/google";
import { HStack, Flex } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <HStack h="100vh" spacing={0}>
          <Flex as="nav" h="full" maxW={16} w="full" bg="gray.100" />
          <Flex
            as="aside"
            h="full"
            maxW="sm"
            w="full"
            borderRightColor="gray.100"
            borderRightWidth={1}
          />
          <Flex
            as="main"
            h="full"
            flex={1}
            borderRightColor="gray.100"
            borderRightWidth={1}
          />
          <Flex as="aside" h="full" maxW="sm" w="full" />
        </HStack>
      </main>
    </>
  );
}
